name: Android Sample

on: [pull_request]

jobs:
#  buildDemo:
#    name: Build Demo JDK ${{ matrix.java_version }}
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: demo/android
#    strategy:
#      matrix:
#        java_version: [1.8, 11, 15]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Install JDK ${{ matrix.java_version }}
#        uses: actions/setup-java@v4
#        with:
#          distribution: "adopt"
#          java-version: ${{ matrix.java_version }}
#      - name: Install Android SDK
#        uses: malinskiy/action-android/install-sdk@release/0.1.1
#      - name: Build project
#        run: ./gradlew assembleDebug

  buildDevelopment:
    name: Build Dev JDK ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo/androidDev
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 11, 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: hannesa2/action-android/install-sdk@0.1.16.7
      - name: Build project
        run: ./gradlew assembleDebug